# Configuration data
LOGFILENAME = ""
TEMPLATENAME = ""
JIGSAWSPATH = ""
PNPNUMBER = ""
BASEDIR = ""
CONFFILEPATH = ""
CONFFILEACCESSED = False
DBNAME = ""

# Kinematic data
ORIGO_LEFT_PSM = int()
UPRIGHT_FROM_ORIGO_LEFT_PSM = int()
DOWNRIGHT_FROM_ORIGO_LEFT_PSM = int()
LEFT_FROM_ORIGO_LEFT_PSM = int()
ABOVE_ORIGO_LEFT_PSM = int()
BELOW_ORIGO_LEFT_PSM = int()


ORIGO_RIGHT_PSM = int()
UPRIGHT_FROM_ORIGO_RIGHT_PSM = int()
DOWNRIGHT_FROM_ORIGO_RIGHT_PSM = int()
LEFT_FROM_ORIGO_RIGHT_PSM = int()
ABOVE_ORIGO_RIGHT_PSM = int()
BELOW_ORIGO_RIGHT_PSM = int()